// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_auth_sign_in from "./routes/api-auth/sign-in.ts";
import * as $api_auth_sign_out from "./routes/api-auth/sign-out.ts";
import * as $api_auth_sign_up from "./routes/api-auth/sign-up.tsx";
import * as $api_middleware from "./routes/api/_middleware.ts";
import * as $api_create_game from "./routes/api/create-game.ts";
import * as $api_create_moves from "./routes/api/create-moves.ts";
import * as $api_submitted_move_id_ from "./routes/api/submitted-move/[id].ts";
import * as $auth_confirm_email from "./routes/auth/confirm-email.tsx";
import * as $auth_sign_in from "./routes/auth/sign-in.tsx";
import * as $auth_sign_up from "./routes/auth/sign-up.tsx";
import * as $game_gameId_ from "./routes/game/[gameId].tsx";
import * as $game_middleware from "./routes/game/_middleware.ts";
import * as $index from "./routes/index.tsx";
import * as $my_games_middleware from "./routes/my-games/_middleware.ts";
import * as $my_games_index from "./routes/my-games/index.tsx";
import * as $AdjacentProvinceSelector from "./islands/AdjacentProvinceSelector.tsx";
import * as $AuthForm from "./islands/AuthForm.tsx";
import * as $CoastialProvinceSelector from "./islands/CoastialProvinceSelector.tsx";
import * as $Controls from "./islands/Controls.tsx";
import * as $ConvoyTheUnit from "./islands/ConvoyTheUnit.tsx";
import * as $CountrySelector from "./islands/CountrySelector.tsx";
import * as $GamePreparationView from "./islands/GamePreparationView.tsx";
import * as $GameView from "./islands/GameView.tsx";
import * as $MoveTheUnit from "./islands/MoveTheUnit.tsx";
import * as $MoveTypeSelector from "./islands/MoveTypeSelector.tsx";
import * as $MovesRenderer from "./islands/MovesRenderer.tsx";
import * as $PlayerGames from "./islands/PlayerGames.tsx";
import * as $SubmittedMoveRenderer from "./islands/SubmittedMoveRenderer.tsx";
import * as $SupportTheUnit from "./islands/SupportTheUnit.tsx";
import * as $UnitSelector from "./islands/UnitSelector.tsx";
import * as $WorldMap from "./islands/WorldMap.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api-auth/sign-in.ts": $api_auth_sign_in,
    "./routes/api-auth/sign-out.ts": $api_auth_sign_out,
    "./routes/api-auth/sign-up.tsx": $api_auth_sign_up,
    "./routes/api/_middleware.ts": $api_middleware,
    "./routes/api/create-game.ts": $api_create_game,
    "./routes/api/create-moves.ts": $api_create_moves,
    "./routes/api/submitted-move/[id].ts": $api_submitted_move_id_,
    "./routes/auth/confirm-email.tsx": $auth_confirm_email,
    "./routes/auth/sign-in.tsx": $auth_sign_in,
    "./routes/auth/sign-up.tsx": $auth_sign_up,
    "./routes/game/[gameId].tsx": $game_gameId_,
    "./routes/game/_middleware.ts": $game_middleware,
    "./routes/index.tsx": $index,
    "./routes/my-games/_middleware.ts": $my_games_middleware,
    "./routes/my-games/index.tsx": $my_games_index,
  },
  islands: {
    "./islands/AdjacentProvinceSelector.tsx": $AdjacentProvinceSelector,
    "./islands/AuthForm.tsx": $AuthForm,
    "./islands/CoastialProvinceSelector.tsx": $CoastialProvinceSelector,
    "./islands/Controls.tsx": $Controls,
    "./islands/ConvoyTheUnit.tsx": $ConvoyTheUnit,
    "./islands/CountrySelector.tsx": $CountrySelector,
    "./islands/GamePreparationView.tsx": $GamePreparationView,
    "./islands/GameView.tsx": $GameView,
    "./islands/MoveTheUnit.tsx": $MoveTheUnit,
    "./islands/MoveTypeSelector.tsx": $MoveTypeSelector,
    "./islands/MovesRenderer.tsx": $MovesRenderer,
    "./islands/PlayerGames.tsx": $PlayerGames,
    "./islands/SubmittedMoveRenderer.tsx": $SubmittedMoveRenderer,
    "./islands/SupportTheUnit.tsx": $SupportTheUnit,
    "./islands/UnitSelector.tsx": $UnitSelector,
    "./islands/WorldMap.tsx": $WorldMap,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
