// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[playerGameId].tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/AdjacentProvinceSelector.tsx";
import * as $$1 from "./islands/CoastialProvinceSelector.tsx";
import * as $$2 from "./islands/Controls.tsx";
import * as $$3 from "./islands/ConvoyTheUnit.tsx";
import * as $$4 from "./islands/CountrySelector.tsx";
import * as $$5 from "./islands/MoveTheUnit.tsx";
import * as $$6 from "./islands/MoveTypeSelector.tsx";
import * as $$7 from "./islands/MovesRenderer.tsx";
import * as $$8 from "./islands/PlayerGames.tsx";
import * as $$9 from "./islands/SupportTheUnit.tsx";
import * as $$10 from "./islands/UnitSelector.tsx";
import * as $$11 from "./islands/WorldMap.tsx";

const manifest = {
  routes: {
    "./routes/[playerGameId].tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/AdjacentProvinceSelector.tsx": $$0,
    "./islands/CoastialProvinceSelector.tsx": $$1,
    "./islands/Controls.tsx": $$2,
    "./islands/ConvoyTheUnit.tsx": $$3,
    "./islands/CountrySelector.tsx": $$4,
    "./islands/MoveTheUnit.tsx": $$5,
    "./islands/MoveTypeSelector.tsx": $$6,
    "./islands/MovesRenderer.tsx": $$7,
    "./islands/PlayerGames.tsx": $$8,
    "./islands/SupportTheUnit.tsx": $$9,
    "./islands/UnitSelector.tsx": $$10,
    "./islands/WorldMap.tsx": $$11,
  },
  baseUrl: import.meta.url,
};

export default manifest;
