// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/api/sign-in.ts";
import * as $2 from "./routes/api/sign-out.ts";
import * as $3 from "./routes/api/sign-up.tsx";
import * as $4 from "./routes/auth/confirm-email.tsx";
import * as $5 from "./routes/auth/sign-in.tsx";
import * as $6 from "./routes/auth/sign-up.tsx";
import * as $7 from "./routes/game/[playerGameId].tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/player/[playerId].tsx";
import * as $$0 from "./islands/AdjacentProvinceSelector.tsx";
import * as $$1 from "./islands/AuthForm.tsx";
import * as $$2 from "./islands/CoastialProvinceSelector.tsx";
import * as $$3 from "./islands/Controls.tsx";
import * as $$4 from "./islands/ConvoyTheUnit.tsx";
import * as $$5 from "./islands/CountrySelector.tsx";
import * as $$6 from "./islands/MoveTheUnit.tsx";
import * as $$7 from "./islands/MoveTypeSelector.tsx";
import * as $$8 from "./islands/MovesRenderer.tsx";
import * as $$9 from "./islands/PlayerGames.tsx";
import * as $$10 from "./islands/SupportTheUnit.tsx";
import * as $$11 from "./islands/UnitSelector.tsx";
import * as $$12 from "./islands/WorldMap.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/api/sign-in.ts": $1,
    "./routes/api/sign-out.ts": $2,
    "./routes/api/sign-up.tsx": $3,
    "./routes/auth/confirm-email.tsx": $4,
    "./routes/auth/sign-in.tsx": $5,
    "./routes/auth/sign-up.tsx": $6,
    "./routes/game/[playerGameId].tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/player/[playerId].tsx": $9,
  },
  islands: {
    "./islands/AdjacentProvinceSelector.tsx": $$0,
    "./islands/AuthForm.tsx": $$1,
    "./islands/CoastialProvinceSelector.tsx": $$2,
    "./islands/Controls.tsx": $$3,
    "./islands/ConvoyTheUnit.tsx": $$4,
    "./islands/CountrySelector.tsx": $$5,
    "./islands/MoveTheUnit.tsx": $$6,
    "./islands/MoveTypeSelector.tsx": $$7,
    "./islands/MovesRenderer.tsx": $$8,
    "./islands/PlayerGames.tsx": $$9,
    "./islands/SupportTheUnit.tsx": $$10,
    "./islands/UnitSelector.tsx": $$11,
    "./islands/WorldMap.tsx": $$12,
  },
  baseUrl: import.meta.url,
};

export default manifest;
